// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import Header from '../components/Header'
import Footer from '@/components/Footer'
import { Poppins } from 'next/font/google'
import { SearchProvider } from './context/SearchContext'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased px-4 md:px-8 lg:px-12 text-[#333333] scroll-smooth`}
      >
        <SearchProvider>
          <Header />
          {children}
          <Footer />
        </SearchProvider>
      </body>
    </html>
  )
}
